name: CI

on:
  push:
    branches: [ "version6" ]
  pull_request:
    branches: [ "version6" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo line 1,
          echo line 2.
          
      - name: Install Dependencies and run test
        run: npm install

