name: CI

on:
  push:
    branches: [ "version6" ]
  pull_request:
    branches: [ "version6" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      
      - name: github action www.cybershit.io
        run: echo "juhu iam a github action"
          
      - name: install dependencies
        run: npm install --force
        
      - name: install playwright
        run: npx playwright install --force
        
      - name: start app
        run: npm start
        
      - name: run test
        run: npx playwright test


